TF.Web/Models/ErrorViewModel.cs
namespace TF.Web.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

TF.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TF.Web.Models;

namespace TF.Web.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

TF.Web/Controllers/WorkItemController.cs
using Microsoft.AspNetCore.Mvc;
using TF.Domain.Models;
using TF.Repository.Repositories;

namespace TF.Web.Controllers;

public class WorkItemController : Controller
{
	readonly private WorkItemRepository _workItemRepository;

    public WorkItemController(WorkItemRepository workItemRepository)
	{
		_workItemRepository = workItemRepository;
	}

    public IActionResult Index()
    {
        IEnumerable<WorkItem> workItems = _workItemRepository.GetAll();
        return View(workItems);
    }
}

TF.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TF.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TF.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TF.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TF.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="WorkItem" asp-action="Index">WorkItems</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TF.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/script.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TF.Web/Views/WorkItem/Index.cshtml
@model IEnumerable<WorkItem>
@{
	ViewData["Title"] = "WorkItems";
}

<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.Name)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Description)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.CreatedAt)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Completed)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.ItemOrder)
			</th>
			<th></th>
		</tr>
	</thead>
	<tbody class="task-list">

		@foreach (var workItem in Model)
		{
			<tr class="task" draggable="true">
				<td>
					@Html.DisplayFor(modelItem => workItem.Name)
				</td>
				<td>
					@Html.DisplayFor(modelItem => workItem.Description)
				</td>
				<td>
					@Html.DisplayFor(modelItem => workItem.CreatedAt)
				</td>
				<td>
					@Html.DisplayFor(modelItem => workItem.Completed)
				</td>
				<td>
					@Html.DisplayFor(modelItem => workItem.ItemOrder)
				</td>
				<td>
					<a class="btn btn-success" asp-action="Editar" asp-route-id="@workItem.Id">Editar</a>
					<a class="btn btn-warning" asp-action="Excluir" asp-route-id="@workItem.Id">Excluir</a>
				</td>
			</tr>
		}
	</tbody>


</table>